export const API_URL = `https://api.unsplash.com`;
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const ACCESS_KEY = 'csYJgbi7H03Sb9pWAU5DA8sAlhc2aKJMDUlqQ7z3SrE';
export const SECRET_KEY = 'QegHHoHFCTT2nAMUC7vvfesYHDg7K2pmcGZfEGmutUA';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const REDIRECT_URI = 'https://dmitriifd.github.io/galllery-js/';
export const RESPONSE_TYPE = 'code';
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const SCOPE = 'public read_user read_photos write_likes';
